# Use postgres/example user/password credentials
version: '3.9'

services:

  app:
    image: 'books-information:latest'
    build:
      context: .
    container_name: books-information
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/books_information
    ports:
      - 8887:8080


  db:
    image: postgres:16.3-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=books_information
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
volumes:
  pgdata:
